export const SETVERSIONS = "SETVERSIONS";
export const SETVALUE1 = "SETVALUE1";
export const SETVALUE2 = "SETVALUE2";
export const SETVALUE = "SETVALUE";
export const ADDVERSIONBOOKS = "ADDVERSIONBOOKS";
